# Generated by Django 4.0.3 on 2022-07-05 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_title', models.CharField(max_length=120)),
                ('prod_price', models.DecimalField(decimal_places=2, default=99.99, max_digits=15)),
                ('prod_quantity', models.IntegerField()),
                ('prod_color', models.CharField(max_length=120)),
                ('prod_image', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('prod_availability', models.BooleanField(default=True)),
                ('prod_description', models.CharField(max_length=120)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.category')),
            ],
        ),
    ]
