# Generated by Django 4.0.3 on 2022-07-05 08:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsLetter',
            fields=[
                ('User_Name', models.CharField(max_length=120)),
                ('User_LastName', models.CharField(max_length=120)),
                ('User_email', models.EmailField(max_length=120)),
                ('User_agreement', models.BooleanField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_delivery_address', models.CharField(max_length=120)),
                ('order_delivery_time', models.DateTimeField()),
                ('order_notes', models.CharField(max_length=120)),
                ('category', models.ManyToManyField(to='account.category')),
                ('product', models.ManyToManyField(to='account.product')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_no_of_items', models.IntegerField()),
                ('cart_total', models.IntegerField()),
                ('category', models.ManyToManyField(to='account.category')),
                ('product', models.ManyToManyField(to='account.product')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
