# Generated by Django 4.0.3 on 2022-07-06 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_category_category_image_category_category_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='Category_Image',
            field=models.ImageField(blank=True, null=True, upload_to='assets/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='prod_image',
            field=models.ImageField(blank=True, null=True, upload_to='api/user/uploads/'),
        ),
    ]
