# Generated by Django 4.0.3 on 2022-07-06 04:09

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_category_category_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='Category_Image',
            field=models.ImageField(blank=True, null=True, upload_to=account.models.upload_path),
        ),
        migrations.AlterField(
            model_name='product',
            name='prod_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
