# Generated by Django 4.0.3 on 2022-07-06 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_alter_category_category_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletter',
            name='user',
        ),
        migrations.AddField(
            model_name='newsletter',
            name='id',
            field=models.BigAutoField(auto_created=True, default=3, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
