# Generated by Django 4.0.3 on 2022-07-06 10:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_remove_newsletter_user_newsletter_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletter',
            name='id',
        ),
        migrations.AddField(
            model_name='newsletter',
            name='user',
            field=models.OneToOneField(default=27, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
