# Generated by Django 4.0.3 on 2022-07-06 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_remove_newsletter_id_newsletter_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsLetter',
        ),
    ]
