# Generated by Django 4.0.3 on 2022-07-07 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_enquiry_id_alter_enquiry_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Enquiry',
        ),
    ]
