# Generated by Django 4.0.3 on 2022-07-07 05:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_delete_enquiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='LetterMain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_Name', models.CharField(max_length=120)),
                ('User_LastName', models.CharField(max_length=120)),
                ('User_email', models.EmailField(max_length=120)),
                ('User_agreement', models.BooleanField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
